

import _ from 'lodash'

export default _.mapKeys([
    'ADD_SUB_PATH',
    'ADD_SUB_PATH_BATCH',
    'CREATE_FILE',
    'CREATE_DIRECTORY',
    'RENAME',
    'DELETE',
    'SHOW_IN_FINDER',
    'DELETE_FILE_METADATA',
    'FETCH_SUB_PATH',
    'ON_FILE_DATA',
    'GET_FILE_DATA',
    'GET_FILE_METADATA',
    'REMOVE_SUB_PATH',
    'REMOVE_SUB_PATH_BATCH',
    'SAVE_SUCCESSFUL',
    'WRITE_FILE_DATA',
    'WRITE_FILE_METADATA',
    'WATCH_PATH',
    'GET_JSON_DATA',
    'UPDATE_JSON_FILE',
    'MODULE_NAVIGATE'
])
