

module.exports={
    'PACKAGER_OUTPUT':'PACKAGER_OUTPUT',
    'RUN_SIMULATOR':'RUN_SIMULATOR',
    'RUN_PACKAGER':'RUN_PACKAGER',
    'STOP_PACKAGER':'STOP_PACKAGER',
    'UPDATE_PACKAGER_STATUS':'UPDATE_PACKAGER_STATUS',
    'RESUME_SIMULATOR':'RESUME_SIMULATOR',
    'RESUME_PACKAGER':'RESUME_PACKAGER',
    'HARD_RELOAD_SIMULATOR':'HARD_RELOAD_SIMULATOR',
    'LIST_AVAILABLE_SIMS':'LIST_AVAILABLE_SIMS',
    'UPDATE_SIMULATOR_STATUS':'UPDATE_SIMULATOR_STATUS'
}

