
module.exports={
    'SAVE_PROJECT':'SAVE_PROJECT',
    'SAVE_AS_PROJECT':'SAVE_AS_PROJECT',
    'SET_PROJECT_DIR':'SET_PROJECT_DIR',
    'CREATE_NEW_PROJECT':'CREATE_NEW_PROJECT',
    'OPEN_PROJECT':'OPEN_PROJECT',
    'SHARE_SAVE_STATUS':'SHARE_SAVE_STATUS',
    'OPEN_PROJECT_SETTINGS':'OPEN_PROJECT_SETTINGS',
    'CUSTOM_CONFIG_ERROR':'CUSTOM_CONFIG_ERROR'
}

