
module.exports={
    CREATE_NEW_PROJECT:'CREATE_NEW_PROJECT',
    OPEN_PROJECT:'OPEN_PROJECT',
    SHARE_SAVE_STATUS:'SHARE_SAVE_STATUS',
    SET_PROJECT_DIR:'SET_PROJECT_DIR',
    SAVE_PROJECT:'SAVE_PROJECT',
    SAVE_AS_PROJECT:'SAVE_AS_PROJECT',
    OPEN_PROJECT_SETTINGS:'OPEN_PROJECT_SETTINGS',
    CUSTOM_CONFIG_ERROR:'CUSTOM_CONFIG_ERROR'
}
